name: Publish NuGet packages
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.1.0-rc.1'
  release:
    types: [published]
jobs:
  verify:
    name: Verify App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      run: dotnet test src/Promitor.Parsers.Prometheus.Tests/Promitor.Parsers.Prometheus.Tests.csproj
  push_nuget_to_ghpr:
    name: Push NuGet packages to NuGet.org
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
    - uses: actions/checkout@v2
    - name: Set version for release trigger
      uses: allenevans/set-env@v2.0.1
      if: ${{ github.event_name == 'release' }}
      with:
        NUGET_VERSION: ${{ github.event.release.tag_name }}
    - name: Set version for workflow dispatch
      uses: allenevans/set-env@v2.0.1
      if: ${{ github.event_name == 'workflow_dispatch' }}
      with:
        NUGET_VERSION: ${{ github.event.inputs.version }}
      # Set NuGet package name since env.NUGET_CORE_PACKAGE_NAME doesn't resolve the variables
    - name: Set NuGet package name (Core)
      uses: allenevans/set-env@v2.0.1
      with:
        NUGET_CORE_PACKAGE_NAME: Promitor.Parsers.Prometheus.Core.${{ env.NUGET_VERSION }}.nupkg
      # Set NuGet package name since env.NUGET_CORE_PACKAGE_PATH doesn't resolve the variables
    - name: Set NuGet package path (Core)
      uses: allenevans/set-env@v2.0.1
      with:
        NUGET_CORE_PACKAGE_PATH: ./src/Promitor.Parsers.Prometheus.Core/bin/Release/${{ env.NUGET_CORE_PACKAGE_NAME }}
      # Set NuGet package name since env.NUGET_HTTP_PACKAGE_NAME doesn't resolve the variables
    - name: Set NuGet package name (HTTP)
      uses: allenevans/set-env@v2.0.1
      with:
        NUGET_HTTP_PACKAGE_NAME: Promitor.Parsers.Prometheus.Http.${{ env.NUGET_VERSION }}.nupkg
      # Set NuGet package name since env.NUGET_HTTP_PACKAGE_PATH doesn't resolve the variables
    - name: Set NuGet package path (HTTP)
      uses: allenevans/set-env@v2.0.1
      with:
        NUGET_HTTP_PACKAGE_PATH: ./src/Promitor.Parsers.Prometheus.Http/bin/Release/${{ env.NUGET_HTTP_PACKAGE_NAME }}
    - name: Build Solution
      run: dotnet build ./src/Promitor.Parsers.Prometheus.sln --configuration Release -p:Version=${{ env.NUGET_VERSION }}
    - name: Push NuGet package (Core)
      run: dotnet nuget push "${{ env.NUGET_CORE_PACKAGE_PATH }}"  --api-key ${{ secrets.NUGET_REGISTRY_NUGETORG_APIKEY }} --source https://api.nuget.org/v3/index.json
    - name: Push NuGet package (HTTP)
      run: dotnet nuget push "${{ env.NUGET_HTTP_PACKAGE_PATH }}"  --api-key ${{ secrets.NUGET_REGISTRY_NUGETORG_APIKEY }} --source https://api.nuget.org/v3/index.json
    - name: Upload NuGet Package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.NUGET_CORE_PACKAGE_NAME }}
        path: ${{ env.NUGET_CORE_PACKAGE_PATH }}
    - name: Upload NuGet Package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.NUGET_HTTP_PACKAGE_NAME }}
        path: ${{ env.NUGET_HTTP_PACKAGE_PATH }}